[project]
name = "pgai-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pgai>=0.11.4",
    "psycopg[binary,pool]>=3.2.9",
    "pydantic-settings>=2.11.0",
]
