log_level = "info"

[server]
port = 8000
readTimeout = "10s"
writeTimeout = "10s"
maxHeaderBytes = 1024

[handler]
requestTimeout = "10s"
swaggerHost = "*"

[embedding]
url = "http://embedding-service:8000"
